title: "Headings"
status: "ready"

context:
  headings:
    -
      message: H1 Heading Styles
      tag: h1
    -
      message: H2 Heading Styles
      tag: h2
    -
      message: H3 Heading Styles
      tag: h3
    -
      message: H4 Heading Styles
      tag: h4

variants:
  -
    name: underlined
    context:
      modifier: h--underlined
      message: Underlined Heading
