title: "Buttons"
status: "ready"

context:
  message: Default Button
  url: '#'

variants:
  -
    name: primary
    context:
      modifier: btn--primary
      message: Primary Button
  -
    name: secondary
    context:
      modifier: btn--secondary
      message: Secondary Button
  -
    name: small
    context:
      modifier: btn--small
      message: Small Button
  -
    name: naked
    context:
      modifier: btn--naked
      message: Naked Button
  -
    name: block
    context:
      modifier: btn--block
      message: Block Display Button
  -
    name: disabled
    context:
      modifier: is--disabled
      message: Disabled Button
