title: "Lists"
status: "ready"

context:
    message: This is a standard list item
    modifier: list

variants:
  -
    name: Numbered List
    context:
      tag: ol
      message: This is a numbered list item
      modifier: list
  -
    name: Unstyled List
    context:
      tag: ul
      modifier: list--unstyled
      message: This is an unstyled list item
