title: "Callout"
status: "ready"

context:
  heading: This is a callout heading
  description: >-
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
