title: "Links"
status: "ready"

context:
  message: This is a standard link item

variants:
  -
    name: primary
    context:
      modifier: link--primary
      message: This is a primary link item
  -
    name: secondary
    context:
      modifier: link--secondary
      message: This is a secondary link item
  -
    name: plain
    context:
      modifier: link--plain
      message: This is a plain link item
  -
    name: bold
    context:
      modifier: link--bold
      message: This is a bold link item
  -
    name: block
    context:
      modifier: link--block
      message: This is a display block link item
