title: "Breadcrumb"
status: "ready"

context:
  breadcrumb:
    items:
      -
        title: Item One
        active: false
      -
        title: Item Two
        active: false
      -
        title: Item Three
        active: false
      -
        title: Current Active Item
        active: true
