title: "Image"
status: "ready"
context:
  src: http://via.placeholder.com/500x500/eeeeee/dddddd
  alt: Placeholder Image
  modifier: img

variants:
  -
    name: full
    context:
      modifier: img--full
