title: "Input"
context:
  input:
    message: Placeholder text
variants:
  -
    name: error
    context:
      modifier: has--error
      input:
        message: I have an error
  -
    name: success
    context:
      modifier: has--success
      input:
        message: I am successful
  -
    name: warninig
    context:
      modifier: has--warning
      input:
        message: I have a warning
  -
    name: password
    context:
      modifier: password
