title: "Button group"
status: "ready"

context:
  name: default
  caption: Nothing

variants:
  -
    name: with-caption
    context:
      modifier: with-caption
      caption: "Caption Note: This is a nice caption example"
