title: "Chevron"
status: "ready"

context:
  modifier: chevron

variants:
  -
    name: up
    context:
      modifier: chevron--up
  -
    name: right
    context:
      modifier: chevron--right
  -
    name: left
    context:
      modifier: chevron--left
  -
    name: primary
    context:
      modifier: chevron--primary
