title: "Chevron"
status: "ready"

variants:
  -
    name: up
    context:
      chevron:
        modifier: chevron--up
  -
    name: right
    context:
      chevron:
        modifier: chevron--right
  -
    name: left
    context:
      chevron:
        modifier: chevron--left
