title: "Hero"
status: "ready"

context:
  subheading: Training for healthcare professionals
  heading: Safeguarding Victims of Modern Slavery
  message: >-
    Transforming the healthcare response to Modern Slavery, ensuring victims and survivors receive excellent trauma-informed care. Evidence-based training that equips front line healthcare professionals with consultation skills to identify, support and safeguard victims and survivors.
  preview:
    noPad: true
