title: "Hero"
status: "ready"

context:
  subheading: Training for healthcare professionals
  heading: Victim Identification and Trafficking Awareness
  message: >-
    Bespoke, evidence-based training packages designed to equip healthcare professionals to identify, support and refer potential victims of modern-day slavery, whilst acting safely and appropriately during a consultation.
  preview:
    noPad: true
