title: "Islands"
status: "ready"

context:
  title: This is an island
  inverse: false

variants:
  -
    name: primary
    context:
      modifier: island--primary
      title: This is a primary island
      inverse: true
  -
    name: secondary
    context:
      modifier: island--secondary
      title: This is a secondary island
      inverse: true
  -
    name: grey
    context:
      modifier: island--grey
      title: This is a grey island
