title: "Flash Message"
status: ready

context:
  message: Flash Message
variants:
  -
    name: success
    context:
      modifier: flash-message--success
      message: Success
  -
    name: warning
    context:
      modifier: flash-message--warning
      message: Warning
  -
    name: danger
    context:
      modifier: flash-message--danger
      message: Danger
